//! Checks the decoder against encodings sampled from GNU objdump.
//!
//! `tests/data/<isa>.tsv` is generated by `scripts/oracle/make_fixtures.py`
//! and covers every mnemonic (with all free bits clear, all set, and random)
//! plus a sample of encodings objdump rejects. The exhaustive version of this
//! test is `examples/oracle_diff.rs`, which nightly CI runs against live objdump.

mod common;

use common::objdump::{Line, compare, isa_by_name};

fn check(name: &str, fixture: &str) {
    let isa = isa_by_name(name).unwrap();
    let failures: Vec<String> = fixture
        .lines()
        .filter_map(|line| compare(&isa, &Line::parse(line)).err())
        .collect();
    assert!(
        failures.is_empty(),
        "{} of {} {name} encodings differ from objdump:\n{}",
        failures.len(),
        fixture.lines().count(),
        failures.join("\n")
    );
}

#[test]
fn esp32_matches_objdump() {
    check("esp32", include_str!("data/esp32.tsv"));
}

#[test]
fn esp32s2_matches_objdump() {
    check("esp32s2", include_str!("data/esp32s2.tsv"));
}

#[test]
fn esp32s3_matches_objdump() {
    check("esp32s3", include_str!("data/esp32s3.tsv"));
}

#[test]
fn esp8266_matches_objdump() {
    check("esp8266", include_str!("data/esp8266.tsv"));
}
